name: starfusion
description: Download STAR-fusion genome resource required to run STAR-Fusion caller
keywords:
  - download
  - starfusion
  - build
  - parabricks

tools:
  - star-fusion:
      description: Fusion calling algorithm for RNAseq data
      homepage: https://github.com/STAR-Fusion/
      documentation: https://github.com/STAR-Fusion/STAR-Fusion/wiki/installing-star-fusion
      tool_dev_url: https://github.com/STAR-Fusion/STAR-Fusion
      doi: "10.1186/s13059-019-1842-9"
      licence: ["GPL v3"]
      identifier: ""
  - "parabricks":
      description: "NVIDIA Clara Parabricks GPU-accelerated genomics tools"
      homepage: "https://www.nvidia.com/en-us/clara/genomics/"
      documentation: "https://docs.nvidia.com/clara/parabricks/latest/index.html"
      licence: ["custom"]
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - reads:
        type: file
        description: fastq.gz files
        pattern: "*.fastq.gz"
        ontologies: []
  - - meta1:
        type: map
        description: Metadata map
        required: true
    - fasta:
        type: file
        description: Input FASTA file
        pattern: "*.{fa,fasta}"
        required: true
        ontologies: []
  - - meta2:
        type: map
        description: Second metadata map
        required: true
    - chimeric_junction:
        type: file
        description: Path to the Chimeric.out.junction file produced by STAR
        pattern: "*.junction"
        required: true
        ontologies: []
  - - meta3:
    - genome_lib_dir:
        type: file
        description: Path to a genome resource library directory. 
        required: true
        ontologies: []
  - - meta4:
        type: map
        description: |
          Groovy Map containing index information
    - index:
        type: file
        description: reference BWA index
        pattern: "*.{amb,ann,bwt,pac,sa}"
        ontologies: []

output:
  reference:
    - - meta:
          type: map
          description: Metadata map
      - ${prefix}_genome_lib_build_dir:
          type: directory
          description: Genome library build directory
          pattern: "*_genome_lib_build_dir"
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@praveenraj2018"
  - "@martings"
  - "@alanmmobbs93"
  - "@delfiterradas"
  - "@sofiromano"

maintainers:
  - "@praveenraj2018"
